# Generated by Django 4.1.2 on 2022-10-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25, verbose_name='Пункт меню')),
                ('slug', models.SlugField(help_text='Имя класса', max_length=25, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'Меню',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='stigmas',
            options={'ordering': ['id'], 'verbose_name': 'Клейма', 'verbose_name_plural': 'Клейма'},
        ),
    ]
