# Generated by Django 4.1.2 on 2022-10-22 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_mainmenu_alter_stigmas_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MainMenu',
        ),
        migrations.AlterModelOptions(
            name='typeanimals',
            options={'ordering': ['id'], 'verbose_name': 'Вид животного', 'verbose_name_plural': 'Вид животного'},
        ),
        migrations.AddField(
            model_name='stigmas',
            name='date_created',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата внесения'),
            preserve_default=False,
        ),
    ]
