# Generated by Django 4.1.2 on 2022-10-23 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_mainmenu_alter_typeanimals_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stigmas',
            name='number',
            field=models.IntegerField(help_text='Введите номер клейма', max_length=6, verbose_name='Номер клейма'),
        ),
    ]
